while True:
      texti=input("Sláðu inn texta ")
      print(texti.upper())
      print(texti.lower())
      print(texti.replace("n","&"))
      print(texti[2:4])
      print(texti[-2:])
      print(texti[::-1])
      print(len(texti))
      print(texti[len(texti)//2])
